EL_FUNC_SIGN(ADD, '+', " + ")
EL_FUNC_SIGN(SUB, '-', " - ")
EL_FUNC_SIGN(MUL, '*', " ")
EL_FUNC_SIGN(DIV, '/', " \\frac")
EL_FUNC_SIGN(POW, '^', "^")

EL_FUNC(LN, "\\ln")
EL_FUNC(SIN, "\\sin")
EL_FUNC(SH, "\\sinh")
EL_FUNC(CH, "\\cosh")
EL_FUNC(TH, "\\tanh")

EL_FUNC(COS, "\\cos")
EL_FUNC(TAN, "\\tan")
EL_FUNC(COT, "\\cot")
EL_FUNC(ASH, "\\arcsinh")
EL_FUNC(ACH, "\\arccosh")
EL_FUNC(ATH, "\\arctanh")
EL_FUNC(ABS, "\\abs")

EL_FUNC(ASIN, "\\arcsin")
EL_FUNC(ACOS, "\\arccos")
EL_FUNC(ATAN, "\\arctan")
EL_FUNC(ACOT, "\\arccot")
EL_FUNC(ACTH, "\\arccoth")
EL_FUNC(SQRT, "\\sqrt")
